/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_rocworks_oc4j_jni_RequestGroup */

#ifndef _Included_at_rocworks_oc4j_jni_RequestGroup
#define _Included_at_rocworks_oc4j_jni_RequestGroup
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_rocworks_oc4j_jni_RequestGroup
 * Method:    getFirstItem
 * Signature: ()Lat/rocworks/oc4j/jni/RequestItem;
 */
JNIEXPORT jobject JNICALL Java_at_rocworks_oc4j_jni_RequestGroup_getFirstItem
  (JNIEnv *, jobject);

/*
 * Class:     at_rocworks_oc4j_jni_RequestGroup
 * Method:    getNextItem
 * Signature: ()Lat/rocworks/oc4j/jni/RequestItem;
 */
JNIEXPORT jobject JNICALL Java_at_rocworks_oc4j_jni_RequestGroup_getNextItem
  (JNIEnv *, jobject);

/*
 * Class:     at_rocworks_oc4j_jni_RequestGroup
 * Method:    getTime1
 * Signature: ()Lat/rocworks/oc4j/var/TimeVar;
 */
JNIEXPORT jobject JNICALL Java_at_rocworks_oc4j_jni_RequestGroup_getTime1
  (JNIEnv *, jobject);

/*
 * Class:     at_rocworks_oc4j_jni_RequestGroup
 * Method:    getTime2
 * Signature: ()Lat/rocworks/oc4j/var/TimeVar;
 */
JNIEXPORT jobject JNICALL Java_at_rocworks_oc4j_jni_RequestGroup_getTime2
  (JNIEnv *, jobject);

/*
 * Class:     at_rocworks_oc4j_jni_RequestGroup
 * Method:    toDebug
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_at_rocworks_oc4j_jni_RequestGroup_toDebug
  (JNIEnv *, jobject, jint);

/*
 * Class:     at_rocworks_oc4j_jni_RequestGroup
 * Method:    malloc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_at_rocworks_oc4j_jni_RequestGroup_malloc
  (JNIEnv *, jobject);

/*
 * Class:     at_rocworks_oc4j_jni_RequestGroup
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_at_rocworks_oc4j_jni_RequestGroup_free
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
