/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_rocworks_oc4j_jni_SysMsg */

#ifndef _Included_at_rocworks_oc4j_jni_SysMsg
#define _Included_at_rocworks_oc4j_jni_SysMsg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_rocworks_oc4j_jni_SysMsg
 * Method:    getSysMsgType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oc4j_jni_SysMsg_getSysMsgType
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
