/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_etm_api_jni_DpMsgHotLink */

#ifndef _Included_com_etm_api_jni_DpMsgHotLink
#define _Included_com_etm_api_jni_DpMsgHotLink
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_etm_api_jni_DpMsgHotLink
 * Method:    malloc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_etm_api_jni_DpMsgHotLink_malloc
  (JNIEnv *, jobject);

/*
 * Class:     com_etm_api_jni_DpMsgHotLink
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_etm_api_jni_DpMsgHotLink_free
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
