/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_etm_api_jni_DpMsg */

#ifndef _Included_com_etm_api_jni_DpMsg
#define _Included_com_etm_api_jni_DpMsg
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
