/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_etm_api_jni_AnswerGroup */

#ifndef _Included_com_etm_api_jni_AnswerGroup
#define _Included_com_etm_api_jni_AnswerGroup
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_etm_api_jni_AnswerGroup
 * Method:    insertItem
 * Signature: (Lcom/etm/api/var/DpIdentifierVar;Lcom/etm/api/var/Variable;Lcom/etm/api/var/TimeVar;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_etm_api_jni_AnswerGroup_insertItem
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_etm_api_jni_AnswerGroup
 * Method:    malloc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_etm_api_jni_AnswerGroup_malloc
  (JNIEnv *, jobject);

/*
 * Class:     com_etm_api_jni_AnswerGroup
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_etm_api_jni_AnswerGroup_free
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
