/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_etm_api_jni_RequestItem */

#ifndef _Included_com_etm_api_jni_RequestItem
#define _Included_com_etm_api_jni_RequestItem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_etm_api_jni_RequestItem
 * Method:    getId
 * Signature: ()Lcom/etm/api/var/DpIdentifierVar;
 */
JNIEXPORT jobject JNICALL Java_com_etm_api_jni_RequestItem_getId
  (JNIEnv *, jobject);

/*
 * Class:     com_etm_api_jni_RequestItem
 * Method:    getNumber
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_etm_api_jni_RequestItem_getNumber
  (JNIEnv *, jobject);

/*
 * Class:     com_etm_api_jni_RequestItem
 * Method:    toDebug
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_etm_api_jni_RequestItem_toDebug
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_etm_api_jni_RequestItem
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_etm_api_jni_RequestItem_free
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
