/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_etm_api_jni_DpMsgRequest */

#ifndef _Included_com_etm_api_jni_DpMsgRequest
#define _Included_com_etm_api_jni_DpMsgRequest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_etm_api_jni_DpMsgRequest
 * Method:    getFirstGroup
 * Signature: ()Lcom/etm/api/jni/RequestGroup;
 */
JNIEXPORT jobject JNICALL Java_com_etm_api_jni_DpMsgRequest_getFirstGroup
  (JNIEnv *, jobject);

/*
 * Class:     com_etm_api_jni_DpMsgRequest
 * Method:    getNextGroup
 * Signature: ()Lcom/etm/api/jni/RequestGroup;
 */
JNIEXPORT jobject JNICALL Java_com_etm_api_jni_DpMsgRequest_getNextGroup
  (JNIEnv *, jobject);

/*
 * Class:     com_etm_api_jni_DpMsgRequest
 * Method:    getMultipleAnswersAllowed
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_etm_api_jni_DpMsgRequest_getMultipleAnswersAllowed
  (JNIEnv *, jobject);

/*
 * Class:     com_etm_api_jni_DpMsgRequest
 * Method:    toString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_etm_api_jni_DpMsgRequest_toString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
