/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_etm_api_jni_DpIdValueList */

#ifndef _Included_com_etm_api_jni_DpIdValueList
#define _Included_com_etm_api_jni_DpIdValueList
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_etm_api_jni_DpIdValueList
 * Method:    toDebug
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_etm_api_jni_DpIdValueList_toDebug
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_etm_api_jni_DpIdValueList
 * Method:    getFirstItem
 * Signature: ()Lcom/etm/api/jni/DpVCItem;
 */
JNIEXPORT jobject JNICALL Java_com_etm_api_jni_DpIdValueList_getFirstItem
  (JNIEnv *, jobject);

/*
 * Class:     com_etm_api_jni_DpIdValueList
 * Method:    getNextItem
 * Signature: ()Lcom/etm/api/jni/DpVCItem;
 */
JNIEXPORT jobject JNICALL Java_com_etm_api_jni_DpIdValueList_getNextItem
  (JNIEnv *, jobject);

/*
 * Class:     com_etm_api_jni_DpIdValueList
 * Method:    cutFirstItem
 * Signature: ()Lcom/etm/api/jni/DpVCItem;
 */
JNIEXPORT jobject JNICALL Java_com_etm_api_jni_DpIdValueList_cutFirstItem
  (JNIEnv *, jobject);

/*
 * Class:     com_etm_api_jni_DpIdValueList
 * Method:    getNumberOfItems
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_etm_api_jni_DpIdValueList_getNumberOfItems
  (JNIEnv *, jobject);

/*
 * Class:     com_etm_api_jni_DpIdValueList
 * Method:    appendItem
 * Signature: (Lcom/etm/api/var/DpIdentifierVar;Lcom/etm/api/var/Variable;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_etm_api_jni_DpIdValueList_appendItem
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_etm_api_jni_DpIdValueList
 * Method:    malloc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_etm_api_jni_DpIdValueList_malloc
  (JNIEnv *, jobject);

/*
 * Class:     com_etm_api_jni_DpIdValueList
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_etm_api_jni_DpIdValueList_free
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
