/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_etm_api_jni_SysMsg */

#ifndef _Included_com_etm_api_jni_SysMsg
#define _Included_com_etm_api_jni_SysMsg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_etm_api_jni_SysMsg
 * Method:    getSysMsgType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_etm_api_jni_SysMsg_getSysMsgType
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
