/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_etm_api_jni_Manager */

#ifndef _Included_com_etm_api_jni_Manager
#define _Included_com_etm_api_jni_Manager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_etm_api_jni_Manager
 * Method:    apiGetLogPath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_etm_api_jni_Manager_apiGetLogPath
  (JNIEnv *, jobject);

/*
 * Class:     com_etm_api_jni_Manager
 * Method:    apiGetDataPath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_etm_api_jni_Manager_apiGetDataPath
  (JNIEnv *, jobject);

/*
 * Class:     com_etm_api_jni_Manager
 * Method:    apiStartup
 * Signature: (I[Ljava/lang/String;ZZ)I
 */
JNIEXPORT jint JNICALL Java_com_etm_api_jni_Manager_apiStartup
  (JNIEnv *, jobject, jint, jobjectArray, jboolean, jboolean);

/*
 * Class:     com_etm_api_jni_Manager
 * Method:    apiShutdown
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_etm_api_jni_Manager_apiShutdown
  (JNIEnv *, jobject);

/*
 * Class:     com_etm_api_jni_Manager
 * Method:    apiDispatch
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_etm_api_jni_Manager_apiDispatch
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_etm_api_jni_Manager
 * Method:    apiDpGet
 * Signature: (Lcom/etm/api/base/JHotLinkWaitForAnswer;[Lcom/etm/api/var/DpIdentifierVar;)I
 */
JNIEXPORT jint JNICALL Java_com_etm_api_jni_Manager_apiDpGet
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     com_etm_api_jni_Manager
 * Method:    apiDpSet
 * Signature: (Lcom/etm/api/base/JHotLinkWaitForAnswer;[Lcom/etm/api/base/JDpVCItem;)I
 */
JNIEXPORT jint JNICALL Java_com_etm_api_jni_Manager_apiDpSet
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     com_etm_api_jni_Manager
 * Method:    apiDpSetTimed
 * Signature: (Lcom/etm/api/base/JHotLinkWaitForAnswer;Lcom/etm/api/var/TimeVar;[Lcom/etm/api/base/JDpVCItem;)I
 */
JNIEXPORT jint JNICALL Java_com_etm_api_jni_Manager_apiDpSetTimed
  (JNIEnv *, jobject, jobject, jobject, jobjectArray);

/*
 * Class:     com_etm_api_jni_Manager
 * Method:    apiDpQuery
 * Signature: (Lcom/etm/api/base/JHotLinkWaitForAnswer;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_etm_api_jni_Manager_apiDpQuery
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_etm_api_jni_Manager
 * Method:    apiDpConnect
 * Signature: (Lcom/etm/api/base/JHotLinkWaitForAnswer;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_etm_api_jni_Manager_apiDpConnect
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_etm_api_jni_Manager
 * Method:    apiDpDisconnect
 * Signature: (Lcom/etm/api/base/JHotLinkWaitForAnswer;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_etm_api_jni_Manager_apiDpDisconnect
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_etm_api_jni_Manager
 * Method:    apiDpConnectArray
 * Signature: (Lcom/etm/api/base/JHotLinkWaitForAnswer;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_etm_api_jni_Manager_apiDpConnectArray
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     com_etm_api_jni_Manager
 * Method:    apiDpDisconnectArray
 * Signature: (Lcom/etm/api/base/JHotLinkWaitForAnswer;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_etm_api_jni_Manager_apiDpDisconnectArray
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     com_etm_api_jni_Manager
 * Method:    apiDpQueryConnectSingle
 * Signature: (Lcom/etm/api/base/JHotLinkWaitForAnswer;ZLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_etm_api_jni_Manager_apiDpQueryConnectSingle
  (JNIEnv *, jobject, jobject, jboolean, jstring);

/*
 * Class:     com_etm_api_jni_Manager
 * Method:    apiDpQueryConnectAll
 * Signature: (Lcom/etm/api/base/JHotLinkWaitForAnswer;ZLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_etm_api_jni_Manager_apiDpQueryConnectAll
  (JNIEnv *, jobject, jobject, jboolean, jstring);

/*
 * Class:     com_etm_api_jni_Manager
 * Method:    apiDpQueryDisonnect
 * Signature: (Lcom/etm/api/base/JHotLinkWaitForAnswer;)I
 */
JNIEXPORT jint JNICALL Java_com_etm_api_jni_Manager_apiDpQueryDisonnect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_etm_api_jni_Manager
 * Method:    apiAlertConnect
 * Signature: (Lcom/etm/api/base/JHotLinkWaitForAnswer;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_etm_api_jni_Manager_apiAlertConnect
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     com_etm_api_jni_Manager
 * Method:    apiAlertDisconnect
 * Signature: (Lcom/etm/api/base/JHotLinkWaitForAnswer;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_etm_api_jni_Manager_apiAlertDisconnect
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     com_etm_api_jni_Manager
 * Method:    apiGetIdSet
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_etm_api_jni_Manager_apiGetIdSet
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_etm_api_jni_Manager
 * Method:    apiGetIdSetOfType
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_etm_api_jni_Manager_apiGetIdSetOfType
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_etm_api_jni_Manager
 * Method:    apiDpGetComment
 * Signature: (Lcom/etm/api/var/DpIdentifierVar;)Lcom/etm/api/var/LangTextVar;
 */
JNIEXPORT jobject JNICALL Java_com_etm_api_jni_Manager_apiDpGetComment
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_etm_api_jni_Manager
 * Method:    apiDoReceiveSysMsg
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_etm_api_jni_Manager_apiDoReceiveSysMsg
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_etm_api_jni_Manager
 * Method:    apiDoReceiveDpMsg
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_etm_api_jni_Manager_apiDoReceiveDpMsg
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_etm_api_jni_Manager
 * Method:    apiSendArchivedDPs
 * Signature: (Lcom/etm/api/var/DynVar;Z)I
 */
JNIEXPORT jint JNICALL Java_com_etm_api_jni_Manager_apiSendArchivedDPs
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     com_etm_api_jni_Manager
 * Method:    apiSetManagerState
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_etm_api_jni_Manager_apiSetManagerState
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_etm_api_jni_Manager
 * Method:    apiProcessHotlinkGroup
 * Signature: (IJ)I
 */
JNIEXPORT jint JNICALL Java_com_etm_api_jni_Manager_apiProcessHotlinkGroup
  (JNIEnv *, jobject, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
